services:
  - type: web
    name: php-sql-lesson
    env: docker
    dockerfilePath: Docker/ubuntu/Dockerfile
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: lesson
      - key: MYSQL_USER
        value: hirotoshiuchida
      - key: MYSQL_PASSWORD
        value: root
