services:
  - type: web
    name: php-mysql-app
    env: docker
    repo: https://github.com/Uchida16104/php-sql-lesson
    branch: master
    dockerContext: Docker/ubuntu
    dockerfilePath: Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: lesson
      - key: MYSQL_USER
        value: hirotoshiuchida
      - key: MYSQL_PASSWORD
        value: root
    plan: free
