services:
  web:
    image: nginx:latest
    container_name: phpdb
    tty: true
    depends_on:
      - mysql
    volumes:
      - "./ubuntu/html:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - '8080:80'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: always

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    volumes:
      - "./ubuntu/mysql:/var/lib/mysql"
      - "./ubuntu/initdb:/docker-entrypoint-initdb.d"
      - "db_data:/var/lib/mysql"
      - "./index.sql:/docker-entrypoint-initdb.d/init.sql"
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lesson
      - MYSQL_USER=hirotoshiuchida
      - MYSQL_PASSWORD=root

  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    ports:
      - "8081:80"

  php:
    build: .
    image: php:8.1-apache
    container_name: php8.1-trial2
    volumes:
      - "./html:/var/www/html"
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - db:mysql

  mysql:
    image: mysql:latest
    container_name: mysql-trial2
    platform: linux/x86_64
    volumes:
      - ".:/var/lib/mysql"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lesson
      - MYSQL_USER=hirotoshiuchida
      - MYSQL_PASSWORD=root

networks:
  default:
    name: phpsql
    driver: bridge

volumes:
  db_data:
