version: "3.9"
services:
  web:
    image: nginx:latest
    build: .
    container_name: phpdb
    tty: true
    depends_on:
      - mysql
    volumes:
      - "./ubuntu/html:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - '8888:80'
    environment:
      - NGINX_HOST='localhost'
      - NGINX_PORT=80
    restart: always
  db:
    image: mysql:latest
    container_name: database
    restart: always
    volumes:
      - "./ubuntu/mysql:/var/lib/mysql"
      - "./ubuntu/initdb:/docker-entrypoint-initdb.d"
    expose: 
      - '3306'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lesson
      - MYSQL_USER=hirotoshiuchida
      - MYSQL_PASSWORD=root
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"
  php:
    image: php:8.1-apache
    container_name: php8.1-trial2
    build: ./php
    volumes:
      - "./html:/var/www/html"
    ports:
      - 8000:80
    depends_on:
      - mysql
    links:
      - db:mysql
  mysql:
    image: mysql:latest
    container_name: mysql-trial2
    platform: linux/x86_64
    volumes:
      - ".:/var/lib/mysql"
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lesson
      - MYSQL_USER=hirotoshiuchida
      - MYSQL_PASSWORD=root
  node:
    build: .
    image: node:latest
    container_name: node.js
    tty: true
    ports: 
      - '8800:80'
    volumes:
      - '/var/lib'
    restart: always
  ruby:
    build: .
    image: ruby:latest
    container_name: ruby
    tty: true
    ports:
      - '8008:80'
    volumes:
      - '/var/lib'
    restart: always
  python3:
    build: .
    image: python3:latest
    container_name: python3
    tty: true
    ports:
      - '8880:80'
    volumes:
      - '/var/lib'
    restart: always
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:latest
    volumes:
      - ./docker-data/wordpress/themes:/var/www/html/wp-content/themes
      - ./docker-data/wordpress/plugins:/var/www/html/wp-content/plugins
      - ./docker-data/wordpress/uploads:/var/www/html/wp-content/uploads
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8088:80"
    environment:
      - WORDPRESS_DB_HOST=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
networks:
  default:
    name: phpsql
    driver: webdb
    external: true
