version: "3.9"
services:
  web:
    build: .
    container_name: phpdb
    tty: true
    depends_on:
      - mysql
    volumes:
      - "./CustomImage/html:/var/www/html"
    ports:
      - '8888:80'
    restart: always
  db:
    image: mysql
    container_name: database
    restart: always
    volumes:
      - "./ubuntu/mysql:/var/lib/mysql"
      - "./ubuntu/initdb:/docker-entrypoint-initdb.d"
    expose: 
      - '3306'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lesson
      - MYSQL_USER=hirotoshiuchida
      - MYSQL_PASSWORD=root
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"
  php:
    image: php:8.1-apache
    container_name: php8.1-trial2
    build: ./php
    volumes:
      - "./html:/var/www/html"
    ports:
      - 8000:80
    depends_on:
      - mysql
    links:
      - db:mysql
  mysql:
    image: mysql
    container_name: mysql-trial2
    platform: linux/x86_64
    volumes:
      - "/var/lib/mysql"
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lesson
      - MYSQL_USER=hirotoshiuchida
      - MYSQL_PASSWORD=root
networks:
  default:
    name: phpsql
    driver: webdb
    external: true
