name: build-in server

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1' ]
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pdo, pdo_mysql

      - name: Node Install and Connect MySQL
        run: npm install mysql && node index.js
        
      - name: Confirm MySQL Firewall
        run: sudo iptables -A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT
      
      - name: Docker process
        run: sudo systemctl status docker && sudo docker ps -a && sudo systemctl restart docker

      - name: Run server
        run: php -S localhost:8000 &

      - name: Access server
        run: curl http://localhost:8000 >> $GITHUB_STEP_SUMMARY
