name: build-in server

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1' ]
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Run server
        run: php -S localhost:8000 &

      - name: Access server
        run: curl http://localhost:8000 >> $GITHUB_STEP_SUMMARY
        
　　　　　　　　　　　- name: start mysql
　　　　　　　　　　　　　　　run: sudo systemctl start mysql.service
