name: build-in server

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1' ]
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          
      - name: Docker process
        run: sudo systemctl status docker && sudo docker ps -a && sudo docker start a5f612f1b4ab4843b1b15592d51c3894_mysql_94ed0b && sudo systemctl restart docker

      - name: Run server
        run: php -S localhost:8000 &

      - name: Access server
        run: curl http://localhost:8000 >> $GITHUB_STEP_SUMMARY
