name: Example

on:
  push:

jobs:
  job-with-mysql:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: foo
          MYSQL_USER: user1
          MYSQL_PASSWORD: user1_password
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Show Docker containers
        run: docker ps -a
      - name: Show databases for root user
        run: mysql -h 127.0.0.1 --port 3306 -u root -phoge_password -e "$(cat $(find ./ -name index.sql))"
