name: Example

on:
  push:

jobs:
  job-with-mysql:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dev
          MYSQL_USER: user
          MYSQL_PASSWORD: root_password
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Show Docker containers
        run: docker ps -a
      - name: Show databases for root user
        run: cd ../ && pwd && ls -l && mysql --protocol=tcp -h localhost -P 3306 -u root -p root < ./index.sql
