name: Example

on:
  push:

jobs:
  job-with-mysql:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dev
          MYSQL_USER: user
          MYSQL_PASSWORD: root_password
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Show Docker containers
        run: docker ps -a
      - name: Show databases for root user
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot_password -e "CREATE DATABASE dev; USE dev; CREATE TABLE param (id INT(3), name VARCHAR(10), class VARCHAR(10), score INT(3)); INSERT INTO param(id, name, class, score) VALUES (1, 'test001', 'A', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (2, 'test002', 'A', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (3, 'test003', 'B', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (4, 'test004', 'A', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (5, 'test005', 'B', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (6, 'test006', 'C', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (7, 'test007', 'A', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (8, 'test008', 'B', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (9, 'test009', 'C', floor(rand()*100)); INSERT INTO param(id, name, class, score) VALUES (10, 'test010', 'D', floor(rand()*100)); SELECT * FROM param;"
