name: PHP Composer
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install php
      - run: brew install php
      - uses: actions/checkout@v2
